# Numpy

In [2]:
import numpy as np

## Trigonometry

In [2]:
cosinus = round(np.cos(np.pi/2),5)
cosinus = np.cos(3.14/2)
print(cosinus)

0.0007963267107332633


In [3]:
np.pi

3.141592653589793

In [4]:
np.deg2rad(90)

np.float64(1.5707963267948966)

## Array creation

In [5]:
# Create array from a list
lst = [1,2,3,4]
print(lst)

arr = np.array(lst)
print(arr)

[1, 2, 3, 4]
[1 2 3 4]


In [6]:
# REGULARLY SPACED ARRAYS
# Start, stop, step size
arr = np.arange(0, 20, 2)
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]


In [7]:
# REGULARLY SPACED ARRAYS
# Start, stop, number of steps
arr = np.linspace(0, 20, 11)
print(arr)

[ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18. 20.]


In [8]:
# Multi-dimensional arrays
arr = np.array([[1,2,3],[4,5,6]])

## Shape and Size

In [9]:
print(f"arr = \n{arr}")
print(f"shape = {arr.shape}")
print(f"ndim = {arr.ndim}")
print(f"size = {arr.size}")

arr = 
[[1 2 3]
 [4 5 6]]
shape = (2, 3)
ndim = 2
size = 6


In [10]:
len(arr.shape)

2

## Indexing

In [11]:
# Element in row 1, column 2
arr[1][2]

np.int64(6)

## Searching

In [12]:
# Get the maximum value
max_value = np.max(arr)

# Get the flat index of the maximum value
flat_index = np.argmax(arr)

# Convert flat index to multi-dimensional index
multi_index = np.unravel_index(flat_index, arr.shape)

print("Array:\n", arr)
print("Maximum Value:", max_value)
print("Flat Index:", flat_index)
print("Multi-dimensional Index:", multi_index)

Array:
 [[1 2 3]
 [4 5 6]]
Maximum Value: 6
Flat Index: 5
Multi-dimensional Index: (np.int64(1), np.int64(2))


In [13]:
# Error
# arr[flat_index]

## Logical & Comparison

In [14]:
# np.where() — Conditional selection
stress = np.array([120, 180, 250, 90])   # MPa
allowable = 200

np.where(stress > allowable, "FAIL", "OK")


array(['OK', 'OK', 'FAIL', 'OK'], dtype='<U4')

In [15]:
# np.any() — Is any element True
overstressed = stress > allowable
np.any(overstressed)


np.True_

In [16]:
# np.all() — Are all elements True
np.all(stress <= allowable)

np.False_

In [17]:
# np.isclose() — Approximate equality

arr_computed = np.array([0.0010001, 0.0020000, 0.0030002])
arr_reference = np.array([0.001, 0.002, 0.003])

np.isclose(arr_computed, arr_reference, rtol=1e-4)


array([ True,  True,  True])

In [18]:
a = 0.1 + 0.2
b = 0.3

print(f"a = {a}, b = {b}")
print(f"a == b: {a == b}")
print(f"np.isclose(a, b): {np.isclose(a, b)}")

a = 0.30000000000000004, b = 0.3
a == b: False
np.isclose(a, b): True


## Array manipulations

In [20]:
# Insertions and deletions
a = np.array([10, 20, 30, 40])
a1 = np.array([[10, 20, 30, 40],[50,60,70,80],[90,100,110,120]])
print(f"a: \n{a}\n")
print(f"a1: \n{a1}\n")

# Insert a single value at index 2
b = np.insert(a, 2, 25)
print(f"np.insert(a, 2, 25): \n{b}\n")

# Delete the element at index 1
c = np.delete(a, 1)
print(f"np.delete(a, 1): \n{c}\n")

# Delete row at index 1
d = np.delete(a1, 1, axis=0)
print(f"np.delete(a1, 1, axis=0): \n{d}\n")

# Append a single value
e = np.append(a, 40)
print(f"np.append(a, 40): \n{e}\n")


a: 
[10 20 30 40]

a1: 
[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]

np.insert(a, 2, 25): 
[10 20 25 30 40]

np.delete(a, 1): 
[10 30 40]

np.delete(a1, 1, axis=0): 
[[ 10  20  30  40]
 [ 90 100 110 120]]

np.append(a, 40): 
[10 20 30 40 40]



In [21]:
# Element-wise operations
a = np.arange(1,10,1).reshape(3,3)
b = np.linspace(1,91,9).reshape(3,3)

print(f"a = \n{a + b}\n")
print(f"a + b = \n{a + b}\n")
print(f"a * b = \n{a * b}\n")
print(f"np.pow(a,2) = \n{np.pow(a,2)}\n")

a = 
[[  2.    14.25  26.5 ]
 [ 38.75  51.    63.25]
 [ 75.5   87.75 100.  ]]

a + b = 
[[  2.    14.25  26.5 ]
 [ 38.75  51.    63.25]
 [ 75.5   87.75 100.  ]]

a * b = 
[[  1.   24.5  70.5]
 [139.  230.  343.5]
 [479.5 638.  819. ]]

np.pow(a,2) = 
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]



In [11]:
arr = np.linspace(1,10,10)
lst = [i for i in range(1,11)]

print(f"lst = {lst} <== list")
print(f"arr = {arr} <== array")
print(f"lst * 3 = {lst * 3} <== copy list three times")
print(f"arr * 3 = {arr * 3} <== element-wise multiplication")

lst = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] <== list
arr = [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.] <== array
lst * 3 = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10] <== copy list three times
arr * 3 = [ 3.  6.  9. 12. 15. 18. 21. 24. 27. 30.] <== element-wise multiplication


## Linear algebra

In [22]:
# Transpose an array
print(f"{arr.T}\n")
print(f"{np.transpose(arr)}\n")
print(f"{arr.transpose()}\n")

[[1 4]
 [2 5]
 [3 6]]

[[1 4]
 [2 5]
 [3 6]]

[[1 4]
 [2 5]
 [3 6]]



In [24]:
# Dot product
a = np.arange(1,10,1).reshape(3,3)
b = np.arange(2,20,2).reshape(3,3)

print(f"np.dot(a,b) = \n{np.dot(a,b)}\n")

np.dot(a,b) = 
[[ 60  72  84]
 [132 162 192]
 [204 252 300]]



In [ ]:
# Matrix multiplication
a = np.arange(1,10,1).reshape(3,3)
b = np.arange(2,20,2).reshape(3,3)

print(f"a @ b = \n{a @ b}\n")
print(f"np.matmul(a,b) = \n{np.matmul(a,b)}\n")

a @ b = 
[[ 60  72  84]
 [132 162 192]
 [204 252 300]]

np.matmul(a,b) = 
[[ 60  72  84]
 [132 162 192]
 [204 252 300]]

a * b = 
[[  2   8  18]
 [ 32  50  72]
 [ 98 128 162]]



In [ ]:
# Element-wise multiplication
print(f"a * b = \n{a * b}\n")

# Matrix multiplication
print(f"a @ b = \n{a @ b}\n")